apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-flow-ui-deployment
  labels:
    app: resume-flow-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-flow-ui
  template:
    metadata:
      labels:
        app: resume-flow-ui
    spec:
      containers:
      - name: resume-flow-ui
        image: resume-flow-ui:latest
        imagePullPolicy: Never
        ports:
         - containerPort: 8002
apiVersion: v1
kind: Service
metadata:
  name: resume-flow-ui-service
spec:
  selector:
    app: resume-flow-ui
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 80
  type: LoadBalancer
